### ISSUE TITLE
any way to show branch name like sublime

### ISSUE THREAD

**Issue by byhwdy** [giovdk21/vscode-sublime-merge#10]
(vs code)
![image](https://user-images.githubusercontent.com/20301466/89158964-6a69f000-d5a1-11ea-88d9-7df4a6f0606f.png)
(sublime)
![image](https://user-images.githubusercontent.com/20301466/89159385-fe3bbc00-d5a1-11ea-9408-9a605ce8943b.png)

**Comment by giovdk21** [comment]
hi byhwdy!

There are a couple of reasons why I'm not showing the name there, please let me know if these make sense to you:
- the two icons in the vscode extension are representing two different informations, so the branch name itself would be confusing
- the branch name is already shown in the status bar on the left hand side; if you set `git.enableStatusBarSync: false` in the setting, you should only see the branch name without the sync button / number of changes

If you'd still like to have the branch name as part of that status bar button I could add it as an optional feature (enabled via settings)

**Comment by byhwdy** [comment]
The branch name can tell me which branch i am workiing on,  and is watched frequently by me at working. It is a very important infomation. And，i like do one thing by one way, by one entrypoint. So, if vscode-sublime-merge provide branch name infomation, i perfer to disable the display of vscode's branch name. Thanks.

**Comment by giovdk21** [comment]
Hello,
you can now show the branch name in the extension status bar item by setting

`"vscsm.showBranchName": true` in your settings

**Comment by byhwdy** [comment]
It is working.
