### ISSUE TITLE
file: path for sublime merge on windows requires forward slashes

### ISSUE THREAD

**Issue by repros896** [giovdk21/vscode-sublime-merge#15]
This is really a bug with sublime merge for windows, but it's unlikely to be fixed there whereas a simple workaround could be added to this extension.  When you send sublime merge the file path the extension is sending what vs code gives it as its uri path, this is encoded correctly with backslashes as ``path\to\file\in\repo`` but sublime merge on windows wants it as ``path/to/file/in/repo``.  As a workaround, I'd propose a configuration argument to use posix paths so that the user of the extension could choose. 

This extension really stands alone amongst its peers in that it works and works like the sublime implementation using the context menu and this is the only issue with using it on windows that I've found, so I'm hopeful that you'll agree to support this workaround.  I do it currently by changing the slashes in sublime merge once it's opened but, as you can imagine, that's a pretty tedious bother.

**Comment by giovdk21** [comment]
hi,
thanks for the feedback!

Just to confirm, this happens when you select "file history..." and "line history...", correct?
Does "blame" work as expected?

Also, as far as I understand with the current version of Sublime Merge for Windows having the option to get the path as `path\to\file\in\repo` is never going to be useful, right? If so I'd just force the posix path also on windows for those commands (if this changes in Sublime Merge, hopefully they will allow both formats for backward compatibility)

**Comment by repros896** [comment]
> Just to confirm, this happens when you select "file history..." and "line history...", correct?

Yes, correct

> Does "blame" work as expected?

It doesn't seem to.  I never use blame in sublime merge but I tested it in sublime to see what to expect and with vs code it never finishes loading, so it does seem that a similar issue is present there.

> Also, as far as I understand with the current version of Sublime Merge for Windows having the option to get the path as path\to\file\in\repo is never going to be useful, right? 

Currently, yes, I think that's correct

> If so I'd just force the posix path also on windows for those commands (if this changes in Sublime Merge, hopefully they will allow both formats for backward compatibility)

This is probably a safe assumption.  Though if you do it as a configuration option then it would be doubly safe. but I'd imagine if they ever fix it they'd need to make it backward compatible.

**Comment by ark-** [comment]
Came here to post this exact issue on Windows. Blame hangs and forward slashes needed in file and line history.

**Comment by giovdk21** [comment]
Thanks for the information.

I'll try to release an update in the upcoming days, at least with a quick fix.

**Comment by ark-** [comment]
Thanks, much appreciated.

**Comment by giovdk21** [comment]
Just published v. 1.3.1 which should fix it 🙂  Please let me know.

**Comment by repros896** [comment]
Fix works great! Thanks for being so responsive

**Comment by ark-** [comment]
Works a treat. Thank you.
