### ISSUE TITLE
Ubuntu 20 click status bar - not work

### ISSUE THREAD

**Issue by gromov-io** [giovdk21/vscode-sublime-merge#18]
Ubuntu 20 click status bar - not work

UPDATE: fixed https://github.com/giovdk21/vscode-sublime-merge/issues/18#issuecomment-846410616

![image](https://user-images.githubusercontent.com/46241127/116792763-62f15c00-aacb-11eb-82cb-7d035ff1e752.png)

**Comment by giovdk21** [comment]
hello!
does it work if you run the "Open repository in Sublime Merge" from the command palette?

If not, from the [extension settings](https://github.com/giovdk21/vscode-sublime-merge#configuration) you could try to manually specify the path to the `smerge` executable.

Please let me know if this helps

**Comment by gromov-io** [comment]
> hello!
> does it work if you run the "Open repository in Sublime Merge" from the command palette?
> 
> If not, from the [extension settings](https://github.com/giovdk21/vscode-sublime-merge#configuration) you could try to manually specify the path to the `smerge` executable.
> 
> Please let me know if this helps


https://user-images.githubusercontent.com/46241127/117220973-0666a780-ae11-11eb-8464-8a65f4333db9.mp4

**Comment by gromov-io** [comment]
> Thanks, could you try enabling debug mode (and restart vscode)
> 
> You should see something like `["INFO" - 4:21:11 PM] Running "/Users/name/bin/smerge" (pid: 3191)`
> 
> (In the "output" tab at the bottom, selecting "sublime merge for vscode" in the dropdown menu)
> 
> ![image](https://user-images.githubusercontent.com/511350/117472216-92331d80-af50-11eb-8cfd-89e154232e28.png)
> 
> edit:
> 
> * I assume running `which smerge` from the terminal (both external and built-in) gives you `/usr/bin/smerge`, correct?
> * Is `/usr/bin/smerge` a link? (in macOs it's a link pointing to a binary executable)

I don't quite understand how to enable debag mod

![image](https://user-images.githubusercontent.com/46241127/117505014-07701400-af8c-11eb-93b8-b8db401dacdd.png)
![image](https://user-images.githubusercontent.com/46241127/117505059-2078c500-af8c-11eb-881c-5daa6095f522.png)

**Comment by giovdk21** [comment]
Hi,
From the extension settings, just below where you specified the path to smerge

**Comment by gromov-io** [comment]
> Привет,
> Из настроек расширения чуть ниже, где вы указали путь к smerge

![image](https://user-images.githubusercontent.com/46241127/117562083-e4855300-b0a4-11eb-8f5d-27e6c76ed645.png)

**Comment by giovdk21** [comment]
vscode seems to be running it fine (it returns a process identifier, `pid: ...`) so I'm not sure why it's not showing up 🤔 

I'd suggest checking if `/usr/bin/smerge` is a link to another executable and in case specify the "destination" path in the settings

**Comment by Syno0** [comment]
Hello, same problem Sublime Merge isn't showing up when clicking on the status bar.
But if Sublime Merge is already open, then it's correctly open the concerned repository.
I tried to set chmod 755 on /user/bin/smerge and also reinstalling sublime merge but no change, maybe a problem with Ubuntu 20.04 and the way of opening Sublime Merge

**Comment by gromov-io** [comment]
I remember exactly that this worked in Ubuntu 18, but stopped working with version 19

**Comment by giovdk21** [comment]
I did manage to give it a go and reproduce the issue installing Ubuntu 20 in VirtualBox... I did try a few things and even using the "open" library, but no luck.

One thing I noticed is that it always only work if the app is already opened and that the first time I try to run a different command (i.e. `smerge`, `gedit`, `firefox`, etc.) it crashes with this message:

![image](https://user-images.githubusercontent.com/511350/119227997-a4908800-bb08-11eb-9f53-8edb78d5c0ec.png)

(this only happen the first times, then afterwards it's silent)

So this seems to be an issue with VSCode / NodeJS + Ubuntu 20

**Comment by giovdk21** [comment]
Ok... don't ask me why this work, but I might have found a solution...

I assume you installed VSCode using the "Ubuntu Software" app or the Ubuntu repo; if so:

- Uninstall VSCode
- Download the official `.deb` file from https://code.visualstudio.com/
- Install the package using `sudo dpkg -i code_1.56.2-1620838498_amd64.deb` (check the filename in case it has changed)

After doing this it works for me 🤷‍♂️
