### ISSUE TITLE
Suggestion: Provide executable path settings for each platform

### ISSUE THREAD

**Issue by RobinWragg** [giovdk21/vscode-sublime-merge#28]
I am using this on macOS and Windows, both work great but it would be beneficial to be able to specify the path to smerge that differ on each platform. Particularly relevant as the feature request for vscode to natively allow platform specific settings seems to be stagnant: https://github.com/microsoft/vscode/issues/5595

**Comment by giovdk21** [comment]
thanks @RobinWragg !
I just pushed version 1.4.0 which allows to specify per-platform executable path settings 🎉
