### ISSUE TITLE
Add line history context menu item for the line with cursor without selection

### ISSUE THREAD

**Issue by certainlyakey** [giovdk21/vscode-sublime-merge#3]
Thanks for the plugin!

One small problem - it took a couple of months for me to notice that line history actually is there in the context menu, because I didn't know that you have to select something for the item to appear. 

Would it be possible to add the line history command to the menu even if there's nothing selected, based on the line cursor is currently in?

**Comment by giovdk21** [comment]
hi,
sorry for the late reply.

This seems related with #1 and I'll try to see if this can be done using a setting; I generally don't like when extensions fill up the contextual menu so that's why blame and line history are hidden unless a selection is present

**Comment by adhamu** [comment]
I don’t want to cannibalise the hard work put into this plugin as it acted as inspiration for my own. 

However, if you’re interested, I’ve developed my own Sublime Merge plugin which has what you’re after.

https://marketplace.visualstudio.com/items?itemName=adhamu.history-in-sublime-merge
